### ISSUE TITLE
OrderedDictionary: Initialize not called on new, empty instance causes crash when enumerating

### ISSUE THREAD

**Issue by danielcrenna** [OndrejPetrzilka/Rock.Collections#1]
m_firstOrderIndex is left in uninitialized state (not -1) when a new instance is created, Initialize is only called when capacity > 0 in constructor, or when adding a new item with null buckets.

The .NET dictionary will simply iterate on the size of the enumerator, but in your case, you check m_firstOrderIndex, which since it is 0 in the uninitialized state, results in a crash trying to get the first element in an empty collection.

`var dict = new OrderedDictionary<string,string>();`
`foreach (var entry in dict) { /* boom */ }`

Our fix is just to change the ctor line to:
`if (capacity >= 0) Initialize(capacity);`

A better fix would preserve your desire for lazy use of memory, and enumerate on the size, similar to the stock .NET.

**Comment by OndrejPetrzilka** [comment]
Thanks for reporting, fixed by 0166dfd
