### ISSUE TITLE
How to access OrderedDictionary using index?

### ISSUE THREAD

**Issue by Mark-Joy** [OndrejPetrzilka/Rock.Collections#3]
Hello,

Thank you for your project!

I have some questions. 
1. How to access OrderedDictionary using index?
2. How to get index of a Key of OrderedDictionary?

**Comment by OndrejPetrzilka** [comment]
You're probably looking for different collection based on your questions, maybe `SortedList` would suit you?

1. Not possible directly, indirect ways will have complexity O(n), e.g. `dictionary.ElementAt(yourIndex)`
2. Not possible directly, indirect ways will have complexity O(n), e.g. `dictionary.TakeWhile(x => x.Key != yourKey).Count();`
